model:
  name: 'hurricane'
  freeze_encoder: true
  output_size: 5
  dropout_weight: 0

train:
  batch_size: 32
  n_epochs: 50
  num_workers: 4

optimizer:
  type: 'adamw'
  lr: 0.0001
  weight_decay: 0.001

loss:
  dice_weight: 1.0
  focal_weight: 8.0
