defaults:
  - network: supervised
  - data: supervised_data
  - trainer: supervised_trainer
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

seed: 42
###To be changed###
model_dir: '/home/hice1/kalyono3/scratch/weights'
###################
log_dir: '/home/hice1/kalyono3/xview2_strong_baseline/logs'
group: 'xview2_supervised'
name: '${group}_lr${network.optimizer.lr}_wd${network.optimizer.weight_decay}_bs${data.labeled_batch_size}_seed${seed}'
ckpt_path: '' # new

logger:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  project: "supervised_xview2"
  group: '${group}'
  name: '${name}'
  save_dir: '${log_dir}'
